# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

customMatrix <- function(z) {
    .Call(`_AdaptiveAllocation_customMatrix`, z)
}

callrgamma <- function(n, shape, scale) {
    .Call(`_AdaptiveAllocation_callrgamma`, n, shape, scale)
}

csample_num <- function(x, size, replace, prob) {
    .Call(`_AdaptiveAllocation_csample_num`, x, size, replace, prob)
}

diracF <- function(a, b) {
    .Call(`_AdaptiveAllocation_diracF`, a, b)
}

summary_Posterior <- function(z) {
    .Call(`_AdaptiveAllocation_summary_Posterior`, z)
}

rdirichlet_cpp <- function(num_samples, alpha_m) {
    .Call(`_AdaptiveAllocation_rdirichlet_cpp`, num_samples, alpha_m)
}

BinderLoss <- function(eAlloc, tAlloc) {
    .Call(`_AdaptiveAllocation_BinderLoss`, eAlloc, tAlloc)
}

coefBinom <- function(n, k) {
    .Call(`_AdaptiveAllocation_coefBinom`, n, k)
}

ari <- function(eAlloc, tAlloc) {
    .Call(`_AdaptiveAllocation_ari`, eAlloc, tAlloc)
}

myProduct <- function(a) {
    .Call(`_AdaptiveAllocation_myProduct`, a)
}

mySum <- function(a) {
    .Call(`_AdaptiveAllocation_mySum`, a)
}

SSG <- function(X, hyper, K, iteration, burnin, thin, method, trueAll) {
    .Call(`_AdaptiveAllocation_SSG`, X, hyper, K, iteration, burnin, thin, method, trueAll)
}

RSSG <- function(X, hyper, K, m, iteration, burnin, thin, method) {
    .Call(`_AdaptiveAllocation_RSSG`, X, hyper, K, m, iteration, burnin, thin, method)
}

JS_distance <- function(p, q) {
    .Call(`_AdaptiveAllocation_JS_distance`, p, q)
}

DiversityGibbsSamp <- function(X, hyper, K, m, iteration, burnin, thin, updateProbAlloc, method, gamma, q, lambda, kWeibull, alphaPareto, xmPareto, DiversityIndex, adaptive) {
    .Call(`_AdaptiveAllocation_DiversityGibbsSamp`, X, hyper, K, m, iteration, burnin, thin, updateProbAlloc, method, gamma, q, lambda, kWeibull, alphaPareto, xmPareto, DiversityIndex, adaptive)
}

CSSG <- function(X, hyper, K, R, iteration, burnin, thin) {
    .Call(`_AdaptiveAllocation_CSSG`, X, hyper, K, R, iteration, burnin, thin)
}

CRSG <- function(X, hyper, K, R, m, iteration, burnin, thin) {
    .Call(`_AdaptiveAllocation_CRSG`, X, hyper, K, R, m, iteration, burnin, thin)
}

CDSG <- function(X, hyper, K, R, m, iteration, burnin, thin, gamma, q) {
    .Call(`_AdaptiveAllocation_CDSG`, X, hyper, K, R, m, iteration, burnin, thin, gamma, q)
}

