# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sum_allocation <- function(z, K) {
    .Call(`_AdaptiveAllocation_sum_allocation`, z, K)
}

callrgamma <- function(n, shape, scale) {
    .Call(`_AdaptiveAllocation_callrgamma`, n, shape, scale)
}

csample_num <- function(x, size, replace, prob) {
    .Call(`_AdaptiveAllocation_csample_num`, x, size, replace, prob)
}

diracF <- function(a, b) {
    .Call(`_AdaptiveAllocation_diracF`, a, b)
}

rdirichlet_cpp <- function(num_samples, alpha_m) {
    .Call(`_AdaptiveAllocation_rdirichlet_cpp`, num_samples, alpha_m)
}

update_allocation <- function(pi, mu, prec, x) {
    .Call(`_AdaptiveAllocation_update_allocation`, pi, mu, prec, x)
}

update_pi <- function(alpha, N) {
    .Call(`_AdaptiveAllocation_update_pi`, alpha, N)
}

update_mu <- function(mu0, p0, prec, z, N, x) {
    .Call(`_AdaptiveAllocation_update_mu`, mu0, p0, prec, z, N, x)
}

update_prec <- function(a0, b0, mu, z, N, x) {
    .Call(`_AdaptiveAllocation_update_prec`, a0, b0, mu, z, N, x)
}

SSG <- function(x, hyper, K, iteration, burnin, thin) {
    .Call(`_AdaptiveAllocation_SSG`, x, hyper, K, iteration, burnin, thin)
}

BinderLoss <- function(eAlloc, tAlloc) {
    .Call(`_AdaptiveAllocation_BinderLoss`, eAlloc, tAlloc)
}

contMat <- function(eAlloc, tAlloc) {
    .Call(`_AdaptiveAllocation_contMat`, eAlloc, tAlloc)
}

update_allocationD <- function(pi, mu, prec, X) {
    .Call(`_AdaptiveAllocation_update_allocationD`, pi, mu, prec, X)
}

update_precDH <- function(a0, b0, mu, z, N, X) {
    .Call(`_AdaptiveAllocation_update_precDH`, a0, b0, mu, z, N, X)
}

update_muDH <- function(mu0, p0, prec, z, N, X) {
    .Call(`_AdaptiveAllocation_update_muDH`, mu0, p0, prec, z, N, X)
}

update_muD <- function(mu0, p0, prec, z, N, X) {
    .Call(`_AdaptiveAllocation_update_muD`, mu0, p0, prec, z, N, X)
}

DSSG <- function(X, hyper, K, iteration, burnin, thin, method, trueAllocation) {
    .Call(`_AdaptiveAllocation_DSSG`, X, hyper, K, iteration, burnin, thin, method, trueAllocation)
}

update_allocationRD <- function(probAllocation, pi, mu, prec, X, m, z, alpha) {
    .Call(`_AdaptiveAllocation_update_allocationRD`, probAllocation, pi, mu, prec, X, m, z, alpha)
}

RSSG <- function(X, hyper, K, m, iteration, burnin, thin, method, trueAllocation) {
    .Call(`_AdaptiveAllocation_RSSG`, X, hyper, K, m, iteration, burnin, thin, method, trueAllocation)
}

GSIndex <- function(probAllocation) {
    .Call(`_AdaptiveAllocation_GSIndex`, probAllocation)
}

entropy <- function(probAllocation) {
    .Call(`_AdaptiveAllocation_entropy`, probAllocation)
}

update_alpha <- function(iter, gamma, alpha_prec, Diversity) {
    .Call(`_AdaptiveAllocation_update_alpha`, iter, gamma, alpha_prec, Diversity)
}

diversity_allocation <- function(probAllocation, m, z, alpha) {
    .Call(`_AdaptiveAllocation_diversity_allocation`, probAllocation, m, z, alpha)
}

DiversityGibbsSamp <- function(X, hyper, K, m, iteration, burnin, thin, method, gamma, diversity, trueAllocation) {
    .Call(`_AdaptiveAllocation_DiversityGibbsSamp`, X, hyper, K, m, iteration, burnin, thin, method, gamma, diversity, trueAllocation)
}

summary_Posterior <- function(z) {
    .Call(`_AdaptiveAllocation_summary_Posterior`, z)
}

